name: 'Create Issue Templateless'
description:
  ' Creates an issue like one would through an Issue Template, but without the
  template '
author: 'benlei'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  fields:
    description: 'The fields to include in the issue'
    required: true

# Define your outputs here.
outputs:
  issue-id:
    description: 'The ID of the issue that was created'

runs:
  using: node20
  main: dist/index.js
