name: 'Create Issue Templateless'
description:
  'Creates or updates an issue like one would through an Issue Template, but
  without the template'
author: 'benlei'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'play'
  color: 'red'

# Define your inputs here.
inputs:
  repository:
    description:
      'The repository to create the issue in. For example, benlei/test-action'
    default: ${{ github.repository }}
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  issue-number:
    description: 'The issue number to update'
    required: false
  update-option:
    description:
      'Update options. Valid values are default, replace, patch, or upsert'
    required: false
    default: 'default'
  title:
    description: 'The title of the issue to find/update'
    required: true
  fields:
    description: 'The fields to include in the issue'
    required: true
  fail-on-error:
    description: 'Whether to fail the action if an error occurs'
    required: false
    default: 'true'

# Define your outputs here.
outputs:
  issue-number:
    description: 'The issue number that was created or updated'
  status:
    description:
      'The status of the action - created if an issue was created, updated if an
      issue was updated, error if an error occurred'

runs:
  using: node20
  main: dist/index.js
