name: 'Create Issue Templateless'
description:
  ' Creates an issue like one would through an Issue Template, but without the
  template '
author: 'benlei'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  title:
    description: 'The title of the issue'
    required: true
  fields:
    description: 'The fields to include in the issue'
    required: true
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false

# Define your outputs here.
outputs:
  issue-id:
    description: 'The issue id that was created'
  issue-number:
    description:
      'The issue number that was created - use this for things like closing
      issues'

runs:
  using: node20
  main: dist/index.js
