import * as dotenvExpand from 'dotenv-expand'

import { Field } from './types'

export const renderIssueBody = (fields: Field[]): string =>
  fields.map(field => `### ${field.key}\n\n${field.value}`).join('\n\n')

export const renderFieldLine = (line: string): Field => {
  const [key, value] = line.split(',', 2).map(field => field.trim())

  if (value && value.startsWith('"') && value.endsWith('"')) {
    const keyName = '__autogenerated' + Math.random().toString(36).substring(7)
    const parsed: Record<string, string> = {}
    parsed[keyName] = value.slice(1, -1)

    const expanded = dotenvExpand.expand({ parsed }).parsed ?? {}
    delete process.env[keyName]

    return {
      key,
      value: expanded[keyName] ?? ''
    }
  }

  return { key, value: value ?? '' }
}
