name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          title: 'Test Issue from CI'
          fields: |
            Release Name, hello-world
            Release Version, v1.0.0
            YAML, "```yaml\nhello: world\nfoo: bar\n```"

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.issue-id }}"

      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ steps.test-action.outputs.issue-id }}
