name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./package.json

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Test Local Action - Update by Number
        id: update-by-number-action
        uses: ./
        with:
          repository: benlei/internal-issues
          github-token: ${{ steps.app-token.outputs.token }}
          issue-number: 12
          title: Update by Issue Number Long Running Issue
          fields: |
            Some Field, Some Value
            Hello, World

      - name: Expected update, but wasnt to correct issue
        if: ${{ steps.update-by-number-action.outputs.issue-number != '12' }}
        run: |
          echo "Issue Number: ${{ steps.update-by-number-action.outputs.issue-number }}"
          exit 1

      - name: Test Local Action - Update by Title
        id: update-by-title-action
        uses: ./
        env:
          PACKAGE_JSON_BLOCK: |
            ```json
            ${{ steps.package.outputs.content }}
            ```
        with:
          repository: benlei/internal-issues
          github-token: ${{ steps.app-token.outputs.token }}
          title: 'Long Running Issue'
          update-option: replace
          fields: |
            Some Field, Some Value
            Hello, World
            package.json, "${PACKAGE_JSON_BLOCK}"
            Foo, Bar

      - name: Expected update, but a new issue was created
        if: ${{ steps.update-by-title-action.outputs.issue-number != '13' }}
        run: |
          echo "Issue Number: ${{ steps.update-by-title-action.outputs.issue-number }}"
          exit 1

      - name: Test Local Action - Create
        id: test-action
        uses: ./
        env:
          PACKAGE_JSON_BLOCK: |
            ```json
            ${{ steps.package.outputs.content }}
            ```
        with:
          repository: benlei/internal-issues
          github-token: ${{ steps.app-token.outputs.token }}
          title: 'Test Issue from CI ${{ github.run_id }}'
          fields: |
            Release Name, hello-world
            Release Version, v1.0.0
            package.json, "${PACKAGE_JSON_BLOCK}"

      - name: Print Create Output
        run: |
          echo "Issue Number: ${{ steps.test-action.outputs.issue-number }}"

      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ steps.test-action.outputs.issue-number }}

  test-partial-update-action:
    name: GitHub Actions Test - Partial Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./package.json

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Test Local Action - Create
        id: test-action
        uses: ./
        env:
          PACKAGE_JSON_BLOCK: |
            ```json
            ${{ steps.package.outputs.content }}
            ```
        with:
          repository: benlei/internal-issues
          github-token: ${{ steps.app-token.outputs.token }}
          title: 'Test Partial Update from CI ${{ github.run_id }}'
          fields: |
            Release Name, hello-world
            Release Version, v1.0.0
            package.json, "${PACKAGE_JSON_BLOCK}"
            Release Author, ${{ github.actor }}

      - name: Print Create Output
        run: |
          echo "Issue Number: ${{ steps.test-action.outputs.issue-number }}"

      - name: Test Local Action - Partial Update
        id: partial-update-action
        uses: ./
        env:
          newVersion: v1.0.1
        with:
          repository: benlei/internal-issues
          github-token: ${{ steps.app-token.outputs.token }}
          update-option: patch
          title: 'Test Partial Update from CI ${{ github.run_id }}'
          fields: |
            Release Name, goodbye, world!
            Release Version, "${newVersion}"
            package.json, **Redacted**
            New Field, Hiya

      - name: Expected update, but a new issue was created
        if:
          ${{ steps.partial-update-action.outputs.issue-number !=
          steps.test-action.outputs.issue-number }}
        run: exit 1

      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ steps.test-action.outputs.issue-number }}
